web:
  image: 'gitlab/gitlab-ee:latest'
  restart: always
  hostname: 'dev.libms.top'
  environment:
    GITLAB_OMNIBUS_CONFIG: |
      external_url 'https://dev.libms.top/gitlab'
      letsencrypt['enable'] = false
      nginx['listen_port'] = 8929
      nginx['listen_https'] = false
      gitlab_rails['gitlab_shell_ssh_port'] = 2224
  ports:
    - '8929:8929'
    - '2224:22'
  volumes:
    - '/srv/gitlab/config:/etc/gitlab'
    - '/srv/gitlab/logs:/var/log/gitlab'
    - '/srv/gitlab/data:/var/opt/gitlab'
